# Generated by Django 4.1 on 2024-09-13 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_app', '0004_alter_transaction_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_to_deposit',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount_to_withdraw',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='check_balance',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
