# Generated by Django 3.0.7 on 2024-09-15 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_app', '0006_alter_transaction_amount_to_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
