# Generated by Django 4.1 on 2024-09-17 06:33

import atm_app.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_app', '0008_alter_transaction_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='amount_to_withdraw',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[atm_app.validators.withdrawal_validator]),
        ),
    ]
