# Generated by Django 5.1.3 on 2024-11-07 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_app', '0011_alter_transaction_amount_to_withdraw'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='balance_after_withdrawal',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
    ]
