# Generated by Django 5.0.6 on 2024-12-02 09:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atm_app', '0015_remove_transaction_amount_to_deposit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account_number',
            field=models.CharField(max_length=12, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(limit_value=12, message='the account number should have 12 digits'), django.core.validators.MaxLengthValidator(limit_value=12, message='the account number should have 12 digits')]),
        ),
    ]
